In [4]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1.

In [20]:
vec2 = np.zeros(10)
vec2[4]=1
vec2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2. Create a vector with values ranging from 10 to 49.

In [8]:
vec1 = np.arange(10,49)
vec1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
np.random.randint(0,8,(3,3))

array([[3, 7, 1],
       [4, 1, 4],
       [4, 4, 0]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [23]:
a = np.array([1,2,0,0,4,0])
a[a>0]


array([1, 2, 4])

In [24]:
a[a<0]

array([], dtype=int32)

In [27]:
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [32]:
data = np.random.randint(100,size=(10,10))
data


array([[92,  2, 68, 78, 77, 31, 45, 55, 28, 81],
       [46, 96, 77, 95, 14, 64, 36, 13, 70, 95],
       [13, 28,  6, 30, 85, 93, 38, 32, 37, 34],
       [30, 83, 75, 56,  6, 40,  9,  9, 59, 56],
       [14, 73, 89, 66, 40, 75,  6,  7, 62, 66],
       [32,  6, 34, 93, 64,  9, 59, 93, 29, 48],
       [ 1, 27, 23, 14, 72, 78, 13, 65, 90, 86],
       [93, 40, 72,  9, 20,  4, 44, 48, 31, 27],
       [ 6, 41, 56, 13, 14, 94,  5, 73, 40, 27],
       [ 5, 20, 10, 61, 61, 39, 70, 51, 16, 75]])

In [33]:
np.min(data)

1

In [34]:
np.max(data)

96

# 6. Create a random vector of size 30 and find the mean value.

In [38]:
vec3 = np.random.random(size=30)
vec3

array([0.89624407, 0.69238519, 0.55904838, 0.48570925, 0.77971416,
       0.96758103, 0.21769502, 0.995675  , 0.7124316 , 0.46359619,
       0.49454366, 0.64642947, 0.88927713, 0.91242861, 0.74365013,
       0.05251533, 0.50122685, 0.89716043, 0.04818765, 0.13039637,
       0.58099348, 0.24360494, 0.74071467, 0.06426531, 0.56668961,
       0.91877279, 0.66417674, 0.86825991, 0.42727602, 0.45295443])

In [39]:
np.mean(vec3)

0.5871201136644957